/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkulator;

import static java.awt.SystemColor.text;

/**
 *
 * @author USER
 */
public class Kalkulatori extends javax.swing.JFrame {

    String angka = "", tipe;
    int pilop, heksa, biner, oktal, bil;
    Double ang1, ang2, jumlah;

    public Kalkulatori() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        o0 = new javax.swing.JButton();
        o1 = new javax.swing.JButton();
        o2 = new javax.swing.JButton();
        o3 = new javax.swing.JButton();
        o4 = new javax.swing.JButton();
        o5 = new javax.swing.JButton();
        o6 = new javax.swing.JButton();
        o7 = new javax.swing.JButton();
        o8 = new javax.swing.JButton();
        o9 = new javax.swing.JButton();
        koma = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        min = new javax.swing.JButton();
        kali = new javax.swing.JButton();
        bagi = new javax.swing.JButton();
        persen = new javax.swing.JButton();
        pangkat = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        equal = new javax.swing.JButton();
        operasi = new javax.swing.JTextField();
        hasil = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        mod1 = new javax.swing.JButton();
        mod2 = new javax.swing.JButton();
        mod3 = new javax.swing.JButton();
        mod4 = new javax.swing.JButton();
        pangkat1 = new javax.swing.JButton();
        mod5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KALKULATOR");
        getContentPane().setLayout(null);

        o0.setBackground(new java.awt.Color(204, 204, 255));
        o0.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        o0.setText("0");
        o0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o0ActionPerformed(evt);
            }
        });
        getContentPane().add(o0);
        o0.setBounds(180, 530, 200, 50);

        o1.setBackground(new java.awt.Color(204, 204, 255));
        o1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        o1.setText("1");
        o1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o1ActionPerformed(evt);
            }
        });
        getContentPane().add(o1);
        o1.setBounds(180, 470, 60, 50);

        o2.setBackground(new java.awt.Color(204, 204, 255));
        o2.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        o2.setText("2");
        o2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o2ActionPerformed(evt);
            }
        });
        getContentPane().add(o2);
        o2.setBounds(250, 470, 60, 50);

        o3.setBackground(new java.awt.Color(204, 204, 255));
        o3.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        o3.setText("3");
        o3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o3ActionPerformed(evt);
            }
        });
        getContentPane().add(o3);
        o3.setBounds(320, 470, 60, 50);

        o4.setBackground(new java.awt.Color(204, 204, 255));
        o4.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        o4.setText("4");
        o4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o4ActionPerformed(evt);
            }
        });
        getContentPane().add(o4);
        o4.setBounds(180, 400, 60, 50);

        o5.setBackground(new java.awt.Color(204, 204, 255));
        o5.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        o5.setText("5");
        o5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o5ActionPerformed(evt);
            }
        });
        getContentPane().add(o5);
        o5.setBounds(250, 400, 60, 50);

        o6.setBackground(new java.awt.Color(204, 204, 255));
        o6.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        o6.setText("6");
        o6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o6ActionPerformed(evt);
            }
        });
        getContentPane().add(o6);
        o6.setBounds(320, 400, 60, 50);

        o7.setBackground(new java.awt.Color(204, 204, 255));
        o7.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        o7.setText("7");
        o7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o7ActionPerformed(evt);
            }
        });
        getContentPane().add(o7);
        o7.setBounds(180, 330, 60, 50);

        o8.setBackground(new java.awt.Color(204, 204, 255));
        o8.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        o8.setText("8");
        o8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o8ActionPerformed(evt);
            }
        });
        getContentPane().add(o8);
        o8.setBounds(250, 330, 60, 50);

        o9.setBackground(new java.awt.Color(204, 204, 255));
        o9.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        o9.setText("9");
        o9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o9ActionPerformed(evt);
            }
        });
        getContentPane().add(o9);
        o9.setBounds(320, 330, 60, 50);

        koma.setBackground(new java.awt.Color(204, 204, 255));
        koma.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        koma.setText(".");
        koma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                komaActionPerformed(evt);
            }
        });
        getContentPane().add(koma);
        koma.setBounds(20, 530, 140, 50);

        plus.setBackground(new java.awt.Color(204, 204, 255));
        plus.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });
        getContentPane().add(plus);
        plus.setBounds(20, 260, 110, 50);

        min.setBackground(new java.awt.Color(204, 204, 255));
        min.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        min.setText("-");
        min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minActionPerformed(evt);
            }
        });
        getContentPane().add(min);
        min.setBounds(140, 260, 100, 50);

        kali.setBackground(new java.awt.Color(204, 204, 255));
        kali.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        kali.setText("X");
        kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliActionPerformed(evt);
            }
        });
        getContentPane().add(kali);
        kali.setBounds(250, 260, 100, 50);

        bagi.setBackground(new java.awt.Color(204, 204, 255));
        bagi.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        bagi.setText("mod");
        bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagiActionPerformed(evt);
            }
        });
        getContentPane().add(bagi);
        bagi.setBounds(20, 380, 140, 37);

        persen.setBackground(new java.awt.Color(204, 204, 255));
        persen.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        persen.setText("%");
        persen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persenActionPerformed(evt);
            }
        });
        getContentPane().add(persen);
        persen.setBounds(20, 330, 140, 40);

        pangkat.setBackground(new java.awt.Color(204, 204, 255));
        pangkat.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        pangkat.setText("^X");
        pangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pangkatActionPerformed(evt);
            }
        });
        getContentPane().add(pangkat);
        pangkat.setBounds(20, 430, 140, 40);

        clear.setBackground(new java.awt.Color(204, 204, 255));
        clear.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        clear.setText("C");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(400, 330, 70, 80);

        equal.setBackground(new java.awt.Color(204, 204, 255));
        equal.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        equal.setText("=");
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });
        getContentPane().add(equal);
        equal.setBounds(400, 420, 70, 160);

        operasi.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        operasi.setToolTipText("");
        operasi.setBorder(null);
        operasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operasiActionPerformed(evt);
            }
        });
        getContentPane().add(operasi);
        operasi.setBounds(330, 90, 140, 30);

        hasil.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hasil.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hasil.setText("0.0");
        hasil.setToolTipText("");
        hasil.setBorder(null);
        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });
        getContentPane().add(hasil);
        hasil.setBounds(20, 90, 450, 90);

        jLabel1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KALKULATOR");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 450, 40);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(170, 320, 220, 280);

        mod1.setBackground(new java.awt.Color(204, 204, 255));
        mod1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        mod1.setText(":");
        mod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mod1ActionPerformed(evt);
            }
        });
        getContentPane().add(mod1);
        mod1.setBounds(360, 260, 110, 50);

        mod2.setBackground(new java.awt.Color(204, 204, 255));
        mod2.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        mod2.setText("tan");
        mod2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mod2ActionPerformed(evt);
            }
        });
        getContentPane().add(mod2);
        mod2.setBounds(250, 200, 100, 50);

        mod3.setBackground(new java.awt.Color(204, 204, 255));
        mod3.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        mod3.setText("sin");
        mod3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mod3ActionPerformed(evt);
            }
        });
        getContentPane().add(mod3);
        mod3.setBounds(20, 200, 110, 50);

        mod4.setBackground(new java.awt.Color(204, 204, 255));
        mod4.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        mod4.setText("cos");
        mod4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mod4ActionPerformed(evt);
            }
        });
        getContentPane().add(mod4);
        mod4.setBounds(140, 200, 100, 50);

        pangkat1.setBackground(new java.awt.Color(204, 204, 255));
        pangkat1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        pangkat1.setText("akar");
        pangkat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pangkat1ActionPerformed(evt);
            }
        });
        getContentPane().add(pangkat1);
        pangkat1.setBounds(20, 480, 140, 40);

        mod5.setBackground(new java.awt.Color(204, 204, 255));
        mod5.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        mod5.setText("log");
        mod5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mod5ActionPerformed(evt);
            }
        });
        getContentPane().add(mod5);
        mod5.setBounds(360, 200, 110, 50);

        setSize(new java.awt.Dimension(501, 629));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void o1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o1ActionPerformed
        // TODO add your handling code here:
        angka += "1";
        operasi.setText(angka);
    }//GEN-LAST:event_o1ActionPerformed

    private void o2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o2ActionPerformed
        // TODO add your handling code here:
        angka += "2";
        operasi.setText(angka);
    }//GEN-LAST:event_o2ActionPerformed

    private void o3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o3ActionPerformed
        // TODO add your handling code here:
        angka += "3";
        operasi.setText(angka);
    }//GEN-LAST:event_o3ActionPerformed

    private void o4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o4ActionPerformed
        // TODO add your handling code here:
        angka += "4";
        operasi.setText(angka);
    }//GEN-LAST:event_o4ActionPerformed

    private void kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliActionPerformed
        // TODO add your handling code here:
        ang1 = Double.parseDouble(angka);
        operasi.setText("X");
        angka = "";
        pilop = 3;
    }//GEN-LAST:event_kaliActionPerformed

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
        // TODO add your handling code here:
        switch (pilop) {
            case 1:
                ang2 = Double.parseDouble(angka);
                jumlah = ang1 + ang2;
                angka = Double.toString(jumlah);
                hasil.setText(angka);
                break;
            case 2:
                ang2 = Double.parseDouble(angka);
                jumlah = ang1 - ang2;
                angka = Double.toString(jumlah);
                hasil.setText(angka);
                break;
            case 3:
                ang2 = Double.parseDouble(angka);
                jumlah = ang1 * ang2;
                angka = Double.toString(jumlah);
                hasil.setText(angka);
                break;
            case 4:
                ang2 = Double.parseDouble(angka);
                jumlah = ang1 / ang2;
                angka = Double.toString(jumlah);
                hasil.setText(angka);
                break;
            case 5:
                jumlah = ang1 / 100;
                angka = Double.toString(jumlah);
                hasil.setText(angka);
                break;
            case 6:
                ang2 = Double.parseDouble(angka);
                jumlah = ang2 % ang1;
                angka = Double.toString(jumlah);
                hasil.setText(angka);
                break;
            case 7:
                ang2 = Double.parseDouble(angka);
                jumlah = Math.pow(ang1, ang2);
                angka = Double.toString(jumlah);
                hasil.setText(angka);
                break;
            case 8:
                jumlah = Math.sin(Math.toRadians(ang1));
                angka = Double.toString(jumlah);
                hasil.setText(angka);
                break;
            case 9:
                jumlah = Math.cos(Math.toRadians(ang1));
                angka = Double.toString(jumlah);
                hasil.setText(angka);
                break;
            case 10:
                jumlah = Math.tan(Math.toRadians(ang1));
                angka = Double.toString(jumlah);
                hasil.setText(angka);
                break;
            case 11:
                jumlah = Math.sqrt(ang1);
                angka = Double.toString(jumlah);
                hasil.setText(angka);
                break;
            case 12:
                jumlah = Math.log10(ang1);
                angka = Double.toString(jumlah);
                hasil.setText(angka);
                break;
        }
        
    }//GEN-LAST:event_equalActionPerformed

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilActionPerformed

    private void o5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o5ActionPerformed
        // TODO add your handling code here:
        angka += "5";
        operasi.setText(angka);
    }//GEN-LAST:event_o5ActionPerformed

    private void o6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o6ActionPerformed
        // TODO add your handling code here:
        angka += "6";
        operasi.setText(angka);
    }//GEN-LAST:event_o6ActionPerformed

    private void o7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o7ActionPerformed
        // TODO add your handling code here:
        angka += "7";
        operasi.setText(angka);
    }//GEN-LAST:event_o7ActionPerformed

    private void o8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o8ActionPerformed
        // TODO add your handling code here:
        angka += "8";
        operasi.setText(angka);
    }//GEN-LAST:event_o8ActionPerformed

    private void o9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o9ActionPerformed
        // TODO add your handling code here:
        angka += "9";
        operasi.setText(angka);
    }//GEN-LAST:event_o9ActionPerformed

    private void o0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o0ActionPerformed
        // TODO add your handling code here:
        angka += "0";
        operasi.setText(angka);
    }//GEN-LAST:event_o0ActionPerformed

    private void komaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_komaActionPerformed
        // TODO add your handling code here:
        angka += ".";
        operasi.setText(angka);
    }//GEN-LAST:event_komaActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        operasi.setText("");
        hasil.setText("");
        ang1 = 0.0;
        ang2 = 0.0;
        jumlah = 0.0;
        angka = "";
    }//GEN-LAST:event_clearActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        // TODO add your handling code here:
        ang1 = Double.parseDouble(angka);
        operasi.setText("+");
        angka = "";
        pilop = 1;
    }//GEN-LAST:event_plusActionPerformed

    private void operasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_operasiActionPerformed

    private void minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minActionPerformed
        // TODO add your handling code here:
        ang1 = Double.parseDouble(angka);
        operasi.setText("-");
        angka = "";
        pilop = 2;
    }//GEN-LAST:event_minActionPerformed

    private void bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiActionPerformed
        // TODO add your handling code here:
        ang1 = Double.parseDouble(angka);
        operasi.setText("mod");
        angka = "";
        pilop = 6;
    }//GEN-LAST:event_bagiActionPerformed

    private void persenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persenActionPerformed
        // TODO add your handling code here:
        ang1 = Double.parseDouble(angka);
        operasi.setText("%");
        angka = "";
        pilop = 5;
    }//GEN-LAST:event_persenActionPerformed

    private void pangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pangkatActionPerformed
        // TODO add your handling code here:
        ang1 = Double.parseDouble(angka);
        operasi.setText("^");
        angka = "";
        pilop = 7;
    }//GEN-LAST:event_pangkatActionPerformed

    private void mod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mod1ActionPerformed
        // TODO add your handling code here:
        ang1 = Double.parseDouble(angka);
        operasi.setText(":");
        angka = "";
        pilop = 4;
    }//GEN-LAST:event_mod1ActionPerformed

    private void mod2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mod2ActionPerformed
        // TODO add your handling code here:
        ang1 = Double.parseDouble(angka);
        operasi.setText("tan");
        angka = "";
        pilop = 10;
    }//GEN-LAST:event_mod2ActionPerformed

    private void mod3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mod3ActionPerformed
        // TODO add your handling code here:
        ang1 = Double.parseDouble(angka);
        operasi.setText("sin");
        angka = "";
        pilop = 8;
    }//GEN-LAST:event_mod3ActionPerformed

    private void mod4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mod4ActionPerformed
        // TODO add your handling code here:
        ang1 = Double.parseDouble(angka);
        operasi.setText("cos");
        angka = "";
        pilop = 9;
    }//GEN-LAST:event_mod4ActionPerformed

    private void pangkat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pangkat1ActionPerformed
        // TODO add your handling code here:
        ang1 = Double.parseDouble(angka);
        operasi.setText("akar");
        angka = "";
        pilop = 11;
    }//GEN-LAST:event_pangkat1ActionPerformed

    private void mod5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mod5ActionPerformed
        // TODO add your handling code here:
        ang1 = Double.parseDouble(angka);
        operasi.setText("log");
        angka = "";
        pilop = 12;
    }//GEN-LAST:event_mod5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulatori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulatori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulatori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulatori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulatori().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bagi;
    private javax.swing.JButton clear;
    private javax.swing.JButton equal;
    private javax.swing.JTextField hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kali;
    private javax.swing.JButton koma;
    private javax.swing.JButton min;
    private javax.swing.JButton mod1;
    private javax.swing.JButton mod2;
    private javax.swing.JButton mod3;
    private javax.swing.JButton mod4;
    private javax.swing.JButton mod5;
    private javax.swing.JButton o0;
    private javax.swing.JButton o1;
    private javax.swing.JButton o2;
    private javax.swing.JButton o3;
    private javax.swing.JButton o4;
    private javax.swing.JButton o5;
    private javax.swing.JButton o6;
    private javax.swing.JButton o7;
    private javax.swing.JButton o8;
    private javax.swing.JButton o9;
    private javax.swing.JTextField operasi;
    private javax.swing.JButton pangkat;
    private javax.swing.JButton pangkat1;
    private javax.swing.JButton persen;
    private javax.swing.JButton plus;
    // End of variables declaration//GEN-END:variables

    private void pilop(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
